[package]
name = "rustide-syntax"
version = "0.1.0"
edition.workspace = true

[dependencies]
ropey = "1.6.1"
streaming-iterator = "0.1.9"
thiserror = "2.0.16"
tree-sitter = "0.24.7"
tree-sitter-cpp = "0.23.4"
tree-sitter-hlsl = "0.2.0"
tree-sitter-python = "0.23.6"

[lints]
workspace = true
